### ISSUE TITLE
Running 'node server.js' in 'host' generates Error

### ISSUE THREAD

**Issue by sscholle** [jamuhl/nodeCQRS#13]
`/nodeCQRS/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/seb/repo/CQRS/nodeCQRS/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/seb/repo/CQRS/nodeCQRS/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:643:30)`

```
$ node -v
v8.9.4
$ npm -v
5.6.0
```

**Comment by jeson114** [comment]
+1
This seems to be a compatibility difference socket.io and node v8.9.4 .EventEmitter is deprecated in high version of node . So upgrading socket.io to latest makes sense . 
P.S socket.io has some changes to it's apis during 0.9 -> latest

**Comment by jamuhl** [comment]
Not using this anymore...feel free to update and provide a PR
